### ISSUE TITLE
just for info

### ISSUE THREAD

**Issue by peter1000** [Nightling/dockerfiles#1]
hi,

just wanted to let you know that I tried your skype image on Arch: and it hanged after pressing *sign in*
![screenshot from 2015-08-24 08-01-43](https://cloud.githubusercontent.com/assets/6168860/9438698/b6ecb026-4a36-11e5-9112-ca84a2a81ff5.png)

---

I also tried firefox but it hanged with:

![screenshot from 2015-08-24 08-07-51](https://cloud.githubusercontent.com/assets/6168860/9438832/ef429502-4a37-11e5-8ab4-75af807f13b0.png)

just for your info

Cheers
P

**Comment by Nightling** [comment]
Hi,

Looks like a mounting issue. Taking ownership of the mounted directories - which are created as root by docker - may not work inside a container. Could you try creating the directories first before you start the scripts? Or chown -R them because they exist now.
In this case: `"${HOME}/.Skype` and `"${HOME}/.mozilla/.mozilla-docker"`

Also, if you're running the scripts as root, it won't work because they use $HOME and $UID. These launchers could use some work. I'm waiting for UID namespaces but maybe mounting passwd would be a better solution than messing with one user.

*PS: Don't be alarmed of force pushes in this repo. I want to keep it small and clean.*

**Comment by peter1000** [comment]
Thanks creating "${HOME}/.mozilla/.mozilla-docker" manually did  open firefox but I had no connection with it. Maybe Skype has a similar issue on my pc.

Anyway thanks.

**Comment by Nightling** [comment]
The network thing is docker related. Maybe routing or DNS?

If you have compatibility issues (with the kernel or X11) you should adopt the Dockerfile(s) to Arch. They're fairly close to each other so you probably won't have to.
